### ISSUE TITLE
Index/Slicing support in NDArray.

### ISSUE THREAD

**Issue by nkreeger** [tensorflow/tfjs-core#408]
NumPy has a nice index/slicing feature that is also implemented in TensorFlow: https://docs.scipy.org/doc/numpy-1.13.0/reference/arrays.indexing.html

Slicing is nice because it allows easy vectorization of a larger data set.

**Comment by nsthorat** [comment]
We have math.slice() already, with the new API change these methods will live on the `NDArray` class itself. We don't have explicit indexing yet so that will be a great improvement (we need to think about how we can provide a terse API in javascript without using the common python bracket notation).

**Comment by nkreeger** [comment]
Oh nice! I didn't see math.slice()!
