### ISSUE TITLE
Help with Inferencing Using Ported TensorFlow Model and Convolutional Layers

### ISSUE THREAD

**Issue by p-buddy** [tensorflow/tfjs-core#674]
Hello,

I'm looking to only run an inference on a ported TensorFlow cnn trained on cifar 10. Can anyone offer some guidance on the easiest way to set up my deeplearn_js model after reading in the variables from checkpoint loader.

The mnist tutorial using checkpoint loader didn't make it clear to me how to support more complex layers, like convolutions. Yet, it feels like it'd be a waste of time to try and adopt the model-builder just to support inferencing. 

Any help would be much appreciated!

**Comment by nkreeger** [comment]
Currently, you have to rebuild the model's inference graph in order to perform inference in deeplearn.js. The mnist sorta reflects how to rebuild the graph + loading the checkpointed weights. We are working on a solution now that loads a saved (frozen) model, automatically converts the graph, exports the weights, and attempts to run inference. Any missing ops will be reported by this tool. Stay tuned for updates as we are in the final stages of design.

**Comment by nkreeger** [comment]
Please see #637

**Comment by p-buddy** [comment]
Great! Thank you — very excited for that release. I'm not so great with doing the graph definitions in typescript.

**Comment by duanhai** [comment]
@nkreeger Hello.Any updates about loading a saved frozen model(*.pb ) .Thx.

**Comment by nsthorat** [comment]
https://github.com/tensorflow/tfjs-converter for more on automatic model conversion with TensorFlow.js
