### ISSUE TITLE
Separated clean documentation for model-builder.

### ISSUE THREAD

**Issue by up-to-you** [tensorflow/tfjs-core#833]
Can you please provide separated doc based on model-builder example ? I think it will cover enough cases  , that will help to start for beginners. Or if you have some videos / books on another resources, please, provide links. Current state of documentation is not enough for comfortable start with your awesome framework.

**Comment by hpssjellis** [comment]
I have heard more examples are coming in the next few months. I have a beginners page of examples in Javascript with some videos, including a fully Javascript simplified version of the model builder called **jj07-mnist.html**. I agree that the more documentation and examples the better. I would really like to see examples of every main machine learning algorithm demonstrated using deeplearnjs.


[https://hpssjellis.github.io/deeplearnjs-javascript-examples/](https://hpssjellis.github.io/deeplearnjs-javascript-examples/)

**Comment by up-to-you** [comment]
@hpssjellis OMG, its awesome !!! This is a light at the end of the tunnel !!! I highly appreciate your work, thanks!

**Comment by tafsiri** [comment]
Yep we are definitely working on some new examples and docs. Stay tuned!

**Comment by hpssjellis** [comment]
> @hpssjellis OMG, its awesome !!! This is a light at the end of the tunnel !!! I highly appreciate your work, thanks!

> https://hpssjellis.github.io/deeplearnjs-javascript-examples/



I think there are about 1 million people who would love to be able to use Machine Learning, and Javascript is definitely the platform to learn it with. I can teach the Javascript, just a bit lacking in Machine Learning. The problem is that until Deeplearnjs becomes stable (version 1.0), spending hours and hours and hours on teaching it, using examples, is a bit of a waste of time as the examples get deprecated.

I hope it doesn't take too long to get examples working, of the approximately 10 Machine Learning platforms using Javascript, I definitely want to stay with the Google PAIR supported Deeplearnjs, but I need working examples to make my [Curriculum](http://rocksetta.com/crowd-curriculum/default.php?playlist=9).

It would also be good to work with a machine learning expert, but my persistence and multiple silly questions tend to scare them away. Doesn't matter how much I learn in Tensorflow, Python, Scikit-Learn, Jupiter Notebook (iPython), it is not easy converting the examples to Javascript

Thanks for the kind words @up-to-you. Might take a while, but I think we can do this.
