### ISSUE TITLE
code for complementary colors

### ISSUE THREAD

**Issue by ZahraMousavi** [tensorflow/tfjs-core#850]

**Comment by ZahraMousavi** [comment]
Hi. I am following the tutorial for complementary-color-predictions in https://deeplearnjs.org/demos/complementary-color-prediction/complementary_color_prediction.html, but I cannot find the code in the repository. I was wondering if anyone can help?

**Comment by ManrajGrover** [comment]
Hi @ZahraMousavi,

Currently, demos are in process of being migrated to eager mode since Graph API is deprecated and now removed from the library for next major release. If you wish to see the code in eager mode, you can checkout #803 which implements the same. You can always visit the history and see the [code](https://github.com/PAIR-code/deeplearnjs/tree/d097071614a876c226c8ce1ddeb955bf530ce64f/demos/complementary-color-prediction) but since the API is deprecated, I wouldn't recommend it.

**Comment by ZahraMousavi** [comment]
Thanks for your help:-)

**Comment by pankajvishwani** [comment]
@ManrajGrover, I think "if" statement should be removed from line#123 otherwise train1Batch function will only be called if shouldFetchCost is set to true.

**Comment by ManrajGrover** [comment]
@pankajvishwani I think you're right. Please feel free to leave the comment in that PR (#803)

**Comment by nsthorat** [comment]
Closing this out - let's move this to Observable or something of that sort. We want to keep the set of examples relatively small.
